### ISSUE TITLE
Add teleproxy functionality into Telepresence

### ISSUE THREAD

**Issue by plombardi89** [datawire/teleproxy#3]
We are going to implement Teleproxy functionality into Telepresence. This requires exploration of whether the teleproxy can be a simple replacement for vpn-tcp or requires being done as a new method.

# Tasks
- [ ] implement teleproxy into telepresence

# CoS
- [ ] a telepresence release that has teleproxy functionality
- [ ] a plan to migrate users to "teleproxy" method

**Comment by rhs** [comment]
This issue as described is quite large in scope. As a first step, I'd like to focus on onboarding other people (starting with Abhay) onto the teleproxy codebase. This makes sense because integrating something only I understand into something only Abhay understands will create a very problematic structure for the overall telepresence project.

Currently the codebase as it exists now is organized as an (almost) single file stream of consciousness implementation of the most expedient path to test a given high level design for how teleproxy can work. Likewise the test suite that exists is similarly aimed at exploring how to provide good/fast coverage for this design as well as exploring how to provide coverage for some additional dimensions of the test matrix that we have not previously considered.

As a first step towards onboarding other people, I'd suggest:

1. I write up/check in a bit more documentation around the high level design being validated here, as well as the testing strategy.
2. Once (1) has been accomplished, Abhay and I can meet, go over the existing code structure, and reorganize it in a more maintainable/testable/onboard-friendly way.

**Comment by ofpiyush** [comment]
If there is some documentation already, I'd like to read it as well. Thank you 👍
